INSERT INTO Meetups VALUES (NULL ,"2015.11.10", "Budapest", "Topic One", "Description One");
INSERT INTO Meetups VALUES (NULL ,"2015.11.12", "Miskolc", "Topic Two", "Description Two");
INSERT INTO Meetups VALUES (NULL ,"2015.11.17", "Budapest", "Topic Three", "Description Three");
INSERT INTO Meetups VALUES (NULL ,"2015.12.10", "Miskolc", "Topic Four", "Description Four");
INSERT INTO Meetups VALUES (NULL ,"2015.12.25", "Budapest", "Topic Five", "Description Five");
INSERT INTO Statuses VALUES (NULL ,"Going");
INSERT INTO Statuses VALUES (NULL ,"Tentative");
INSERT INTO Statuses VALUES (NULL ,"Not going");
INSERT INTO Statuses VALUES (NULL ,"Presenting");
INSERT INTO Statuses VALUES (NULL ,"Going");
INSERT INTO Users VALUES (NULL ,"Person One", "1991.06.30", "Codecool student", "???", "personone@gmail.com");
INSERT INTO Users VALUES (NULL ,"Person Two", "1992.08.06", "Freelancer", "???", "persontwo@gmail.com");
INSERT INTO Users VALUES (NULL ,"Person Three", "1992.09.14", "Freelancer", "???", "personthree@gmail.com");
INSERT INTO Users VALUES (NULL ,"Person Four", "1990.04.03", "Codecool studnt", "???", "personfour@gmail.com");
INSERT INTO Users VALUES (NULL ,"Person Five", "1989.11.16", "Mentor", "???", "personfive@gmail.com");
INSERT INTO MeetupRegistrations VALUES (NULL , 1, 4, 2);
INSERT INTO MeetupRegistrations VALUES (NULL , 1, 5, 2);
INSERT INTO MeetupRegistrations VALUES (NULL , 4, 4, 1);
INSERT INTO MeetupRegistrations VALUES (NULL , 1, 4, 4);
INSERT INTO MeetupRegistrations VALUES (NULL , 1, 5, 4);